<!--
  PrintableDocumentView — a minimal, print-optimized view of a document.
  Designed to be rendered in a separate window, iframe, or modal
  before calling window.print().
-->
<script lang="ts">
	import RichMarkdownViewer from './RichMarkdownViewer.svelte';

	/** Document title */
	export let title: string = '';

	/** Markdown content */
	export let content: string = '';

	/** Optional module/path label */
	export let label: string = '';

	/** Optional export date */
	export let date: string = new Date().toLocaleDateString();

	/** Whether to show the header (title, date, label) */
	export let showHeader: boolean = true;
</script>

<div class="printable-document-view">
	{#if showHeader}
		<header class="print-header">
			<div class="print-meta">
				{#if label}
					<span class="print-label">{label}</span>
				{/if}
				<span class="print-date">{date}</span>
			</div>
			<h1 class="print-title">{title}</h1>
		</header>
	{/if}

	<main class="print-content">
		<RichMarkdownViewer {content} />
	</main>

	<footer class="print-footer">
		<p>Generated by RustShare</p>
	</footer>
</div>

<style>
	.printable-document-view {
		max-width: 800px;
		margin: 0 auto;
		padding: 2rem;
		background: #white;
		color: #000;
		font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
	}

	.print-header {
		margin-bottom: 2rem;
		border-bottom: 2px solid #eee;
		padding-bottom: 1rem;
	}

	.print-meta {
		display: flex;
		justify-content: space-between;
		font-size: 0.75rem;
		color: #666;
		margin-bottom: 0.5rem;
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.print-title {
		font-size: 2.25rem;
		font-weight: 800;
		margin: 0;
		color: #000;
		line-height: 1.2;
	}

	.print-content {
		line-height: 1.6;
	}

	/* Ensure Tiptap elements look good in print */
	.print-content :global(.editor-container) {
		padding: 0 !important;
	}

	.print-footer {
		margin-top: 4rem;
		padding-top: 1rem;
		border-top: 1px solid #eee;
		font-size: 0.75rem;
		color: #999;
		text-align: center;
	}

	@media print {
		.printable-document-view {
			padding: 0;
			max-width: none;
		}

		.print-footer {
			position: fixed;
			bottom: 0;
			width: 100%;
		}
		
		/* Force background colors and colors in print */
		* {
			-webkit-print-color-adjust: exact !important;
			print-color-adjust: exact !important;
		}
		
		/* Avoid breaking inside important elements */
		.print-content :global(h1),
		.print-content :global(h2),
		.print-content :global(h3),
		.print-content :global(img),
		.print-content :global(table),
		.print-content :global(blockquote),
		.print-content :global(pre) {
			page-break-inside: avoid;
		}
	}
</style>
