[package]
name = "rustshare-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
thiserror = { workspace = true }
async-trait = "0.1"
sqlx = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
rustshare-crypto = { path = "../crypto" }
url = "2.5"
reqwest = { workspace = true }
image = { version = "0.25", default-features = false, features = ["webp", "png", "jpeg", "gif"] }
lettre = { version = "0.11", default-features = false, features = ["builder", "smtp-transport", "tokio1-rustls-tls", "pool"] }
mailparse = "0.16"
utoipa = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
