/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RustShareVaultSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  rustshareUrl: "https://rustshare.io",
  authToken: "",
  deviceId: "",
  deviceName: "",
  vaultId: "",
  autoSyncIntervalMinutes: 0,
  conflictStrategy: "create_copy",
  debounceMs: 1500,
  maxRetries: 5,
  retryBaseDelayMs: 2e3,
  logSyncEvents: false
};

// src/ui/settings-tab.ts
var import_obsidian = require("obsidian");
var RustShareVaultSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "RustShare Vault Sync Settings" });
    containerEl.createEl("p", {
      text: "Obsidian is a trademark of Dynalist Inc. RustShare is not affiliated with, endorsed by, or sponsored by Obsidian.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("RustShare URL").setDesc("The URL of your RustShare instance").addText((text) => text.setPlaceholder("https://rustshare.io").setValue(this.plugin.settings.rustshareUrl).onChange(async (value) => {
      this.plugin.settings.rustshareUrl = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("p", {
      text: 'To connect, run the "Connect or create vault" command and follow the pairing instructions.',
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Device name").setDesc("A friendly name for this device").addText((text) => text.setPlaceholder("My MacBook").setValue(this.plugin.settings.deviceName).onChange(async (value) => {
      this.plugin.settings.deviceName = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Vault ID").setDesc("The RustShare vault ID to sync with (leave empty to create new)").addText((text) => text.setPlaceholder("Optional vault ID").setValue(this.plugin.settings.vaultId).onChange(async (value) => {
      this.plugin.settings.vaultId = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-sync interval").setDesc("Minutes between automatic syncs (0 to disable)").addText((text) => text.setPlaceholder("0").setValue(String(this.plugin.settings.autoSyncIntervalMinutes)).onChange(async (value) => {
      const num = parseInt(value, 10);
      this.plugin.settings.autoSyncIntervalMinutes = isNaN(num) ? 0 : Math.max(0, num);
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Advanced Sync Settings" });
    new import_obsidian.Setting(containerEl).setName("Save debounce (ms)").setDesc("Milliseconds to wait after a file change before syncing").addText((text) => text.setPlaceholder("1500").setValue(String(this.plugin.settings.debounceMs)).onChange(async (value) => {
      const num = parseInt(value, 10);
      this.plugin.settings.debounceMs = isNaN(num) ? 1500 : Math.max(100, num);
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Max retries").setDesc("Maximum retry attempts when offline").addText((text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.maxRetries)).onChange(async (value) => {
      const num = parseInt(value, 10);
      this.plugin.settings.maxRetries = isNaN(num) ? 5 : Math.max(0, num);
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Retry base delay (ms)").setDesc("Base delay between retries (doubles each attempt)").addText((text) => text.setPlaceholder("2000").setValue(String(this.plugin.settings.retryBaseDelayMs)).onChange(async (value) => {
      const num = parseInt(value, 10);
      this.plugin.settings.retryBaseDelayMs = isNaN(num) ? 2e3 : Math.max(500, num);
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Log sync events").setDesc("Enable in-memory sync logging for debugging").addToggle((toggle) => toggle.setValue(this.plugin.settings.logSyncEvents).onChange(async (value) => {
      this.plugin.settings.logSyncEvents = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/ui/status-bar.ts
var StatusBar = class {
  constructor(plugin) {
    __publicField(this, "statusBarItemEl");
    __publicField(this, "currentStatus", "disconnected");
    this.statusBarItemEl = plugin.addStatusBarItem();
    this.statusBarItemEl.addClass("rustshare-sync-status");
    this.updateStatus("disconnected");
  }
  updateStatus(status, message) {
    this.currentStatus = status;
    this.statusBarItemEl.empty();
    const iconEl = this.statusBarItemEl.createEl("span", { cls: "rustshare-sync-status-icon" });
    const textEl = this.statusBarItemEl.createEl("span", { text: message || this.statusText(status) });
    this.statusBarItemEl.removeClass(
      "rustshare-sync-status--disconnected",
      "rustshare-sync-status--connected",
      "rustshare-sync-status--syncing",
      "rustshare-sync-status--synced",
      "rustshare-sync-status--conflict",
      "rustshare-sync-status--error",
      "rustshare-sync-status--offline"
    );
    this.statusBarItemEl.addClass(`rustshare-sync-status--${status}`);
  }
  statusText(status) {
    switch (status) {
      case "disconnected":
        return "RustShare: Disconnected";
      case "connected":
        return "RustShare: Connected";
      case "syncing":
        return "RustShare: Syncing...";
      case "synced":
        return "RustShare: Synced";
      case "conflict":
        return "RustShare: Conflict";
      case "error":
        return "RustShare: Error";
      case "offline":
        return "RustShare: Offline";
    }
  }
};

// src/api.ts
var RustShareAPI = class {
  constructor(baseUrl, authToken) {
    this.baseUrl = baseUrl;
    this.authToken = authToken;
    this.validateBaseUrl(baseUrl);
  }
  validateBaseUrl(url) {
    try {
      const parsed = new URL(url);
      const allowed = parsed.protocol === "https:" || parsed.protocol === "http:" && /^localhost(:\d+)?$/.test(parsed.hostname);
      if (!allowed) {
        throw new Error(`Invalid URL scheme: ${parsed.protocol}. Only HTTPS is allowed.`);
      }
      if (parsed.username || parsed.password) {
        throw new Error("URL must not contain credentials");
      }
    } catch (e) {
      if (e instanceof TypeError) {
        throw new Error(`Invalid URL: ${url}`);
      }
      throw e;
    }
  }
  buildUrl(endpoint) {
    return `${this.baseUrl.replace(/\/$/, "")}/api/vault-sync/v1${endpoint}`;
  }
  encodePath(path) {
    return path.replace(/\/+/g, "/").split("/").map(encodeURIComponent).join("/");
  }
  getMimeType(path) {
    var _a;
    const ext = (_a = path.split(".").pop()) == null ? void 0 : _a.toLowerCase();
    switch (ext) {
      case "md":
        return "text/markdown";
      case "txt":
        return "text/plain";
      case "png":
        return "image/png";
      case "jpg":
      case "jpeg":
        return "image/jpeg";
      case "gif":
        return "image/gif";
      case "svg":
        return "image/svg+xml";
      case "pdf":
        return "application/pdf";
      case "json":
        return "application/json";
      case "js":
        return "application/javascript";
      case "css":
        return "text/css";
      case "html":
      case "htm":
        return "text/html";
      default:
        return "application/octet-stream";
    }
  }
  fetchWithTimeout(url, init, timeoutMs = 3e4) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), timeoutMs);
    return fetch(url, { ...init, signal: controller.signal }).finally(() => {
      clearTimeout(timeout);
    });
  }
  async request(method, endpoint, body, extraHeaders) {
    var _a, _b, _c, _d, _e, _f;
    const headers = {};
    if (this.authToken) {
      headers["Authorization"] = `Bearer ${this.authToken}`;
    }
    Object.assign(headers, extraHeaders);
    if (body !== void 0 && !(body instanceof ArrayBuffer) && !headers["Content-Type"]) {
      headers["Content-Type"] = "application/json";
    }
    const response = await this.fetchWithTimeout(this.buildUrl(endpoint), {
      method,
      headers,
      body: body instanceof ArrayBuffer ? body : body !== void 0 ? JSON.stringify(body) : void 0
    });
    if (response.status === 409) {
      const conflict = await response.json().catch(() => ({}));
      const error = {
        error: "conflict",
        message: (_a = conflict.message) != null ? _a : "Conflict detected",
        path: (_b = conflict.path) != null ? _b : endpoint,
        client_rev: (_c = conflict.client_rev) != null ? _c : 0,
        current_rev: (_d = conflict.current_rev) != null ? _d : 0,
        server_sha256: conflict.server_sha256,
        resolution: (_e = conflict.resolution) != null ? _e : "create_conflict_copy"
      };
      const err = new Error(error.message || "Conflict");
      Object.assign(err, error);
      throw err;
    }
    if (response.status === 429) {
      const retryAfter = response.headers.get("retry-after") || response.headers.get("Retry-After");
      let retryAfterSeconds;
      if (retryAfter) {
        const trimmed = retryAfter.trim();
        if (/^\d+$/.test(trimmed)) {
          retryAfterSeconds = parseInt(trimmed, 10);
        }
      }
      const text = await response.text();
      const err = new Error(`HTTP 429: ${text}`);
      err.status = 429;
      err.retry_after = retryAfterSeconds;
      throw err;
    }
    if (!response.ok) {
      const text = await response.text().catch(() => "Unknown error");
      throw new Error(`HTTP ${response.status}: ${text}`);
    }
    if (response.status === 204) {
      return void 0;
    }
    const contentType = (_f = response.headers.get("Content-Type")) != null ? _f : "";
    if (contentType.includes("application/json")) {
      return response.json();
    }
    return response.arrayBuffer();
  }
  // Device pairing methods
  async requestDevicePairing() {
    return this.request("POST", "/auth/device/request");
  }
  async pollDevicePairing(deviceCode) {
    return this.request("POST", "/auth/device/poll", { device_code: deviceCode });
  }
  // Vault methods
  async createVault(req) {
    return this.request("POST", "/vaults", req);
  }
  async listVaults() {
    return this.request("GET", "/vaults");
  }
  async getVault(vaultId) {
    return this.request("GET", `/vaults/${encodeURIComponent(vaultId)}`);
  }
  async getManifest(vaultId) {
    return this.request("GET", `/vaults/${encodeURIComponent(vaultId)}/manifest`);
  }
  // File methods
  async uploadFile(vaultId, path, content, sha256, baseServerRev, deviceId) {
    return this.request("PUT", `/vaults/${encodeURIComponent(vaultId)}/files/${this.encodePath(path)}`, content, {
      "Content-Type": this.getMimeType(path),
      "X-RustShare-Base-Server-Rev": String(baseServerRev),
      "X-RustShare-SHA256": sha256,
      "X-RustShare-Device-ID": deviceId
    });
  }
  async downloadFile(vaultId, path) {
    return this.request("GET", `/vaults/${encodeURIComponent(vaultId)}/files/${this.encodePath(path)}`);
  }
  async deleteFile(vaultId, path, baseServerRev, deviceId) {
    await this.request("DELETE", `/vaults/${encodeURIComponent(vaultId)}/files/${this.encodePath(path)}`, void 0, {
      "X-RustShare-Base-Server-Rev": String(baseServerRev),
      "X-RustShare-Device-ID": deviceId
    });
  }
  async renameFile(vaultId, req) {
    const { old_path, new_path, base_server_rev, device_id } = req;
    await this.request("POST", `/vaults/${encodeURIComponent(vaultId)}/rename`, { old_path, new_path }, {
      "X-RustShare-Base-Server-Rev": String(base_server_rev),
      "X-RustShare-Device-ID": device_id
    });
  }
  // Device methods
  async registerDevice(deviceName, clientType, clientVersion) {
    return this.request("POST", "/devices/register", {
      device_name: deviceName,
      client_type: clientType,
      client_version: clientVersion
    });
  }
  async revokeDevice(deviceId) {
    await this.request("DELETE", `/devices/${encodeURIComponent(deviceId)}`);
  }
};

// src/sync.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
async function sha256ArrayBuffer(data) {
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}
function formatConflictFileName(originalPath, deviceName, date) {
  const lastDot = originalPath.lastIndexOf(".");
  const ext = lastDot > 0 ? originalPath.slice(lastDot) : "";
  const basename = lastDot > 0 ? originalPath.slice(0, lastDot) : originalPath;
  const lastSlash = basename.lastIndexOf("/");
  const dir = lastSlash >= 0 ? basename.slice(0, lastSlash + 1) : "";
  const name = lastSlash >= 0 ? basename.slice(lastSlash + 1) : basename;
  const timestamp = date.toISOString().replace(/[-:T]/g, "").slice(0, 12);
  const safeDeviceName = deviceName.replace(/[^a-zA-Z0-9_-]/g, "_");
  return `${dir}${name} (RustShare conflicted copy ${safeDeviceName} ${timestamp})${ext}`;
}
var DEFAULT_IGNORED_PATHS = [
  ".obsidian/",
  ".git/",
  ".DS_Store",
  "node_modules/",
  "Thumbs.db",
  ".rustshare-sync-state.json"
];
function shouldIgnorePath(path) {
  for (const ignored of DEFAULT_IGNORED_PATHS) {
    if (ignored.endsWith("/")) {
      if (path.startsWith(ignored) || path.includes("/" + ignored)) return true;
    } else {
      if (path === ignored || path.endsWith("/" + ignored)) return true;
    }
  }
  return false;
}
function detectCloudSyncFolder(vaultPath) {
  const cloudIndicators = ["Dropbox", "iCloud Drive", "OneDrive", "Google Drive", "Box Sync", "pCloud"];
  for (const indicator of cloudIndicators) {
    if (vaultPath.includes(indicator)) return indicator;
  }
  return null;
}

// src/sync-log.ts
var SyncLog = class {
  constructor(maxEntries = 500) {
    this.maxEntries = maxEntries;
    __publicField(this, "buffer");
    __publicField(this, "head");
    __publicField(this, "count");
    this.buffer = new Array(maxEntries);
    this.head = 0;
    this.count = 0;
  }
  push(level, message, path, error) {
    const entry = {
      timestamp: (/* @__PURE__ */ new Date()).toISOString(),
      level,
      message,
      path,
      error
    };
    this.buffer[this.head] = entry;
    this.head = (this.head + 1) % this.maxEntries;
    if (this.count < this.maxEntries) {
      this.count++;
    }
  }
  debug(message, path) {
    this.push("debug", message, path);
  }
  info(message, path) {
    this.push("info", message, path);
  }
  warn(message, path) {
    this.push("warn", message, path);
  }
  error(message, path, error) {
    this.push("error", message, path, error);
  }
  getRecent(limit) {
    const result = [];
    const max = limit !== void 0 ? Math.min(limit, this.count) : this.count;
    for (let i = 0; i < max; i++) {
      const idx = (this.head - 1 - i + this.maxEntries) % this.maxEntries;
      const entry = this.buffer[idx];
      if (entry !== void 0) {
        result.push(entry);
      }
    }
    return result;
  }
  clear() {
    this.buffer = new Array(this.maxEntries);
    this.head = 0;
    this.count = 0;
  }
};
var syncLog = new SyncLog();

// src/sync.ts
var UploadConflictError = class extends Error {
  constructor(path, serverSha256, currentRev) {
    super(`Conflict uploading ${path}`);
    this.path = path;
    this.serverSha256 = serverSha256;
    this.currentRev = currentRev;
  }
};
var SyncEngine = class {
  constructor(vault, api, state, deviceName) {
    this.vault = vault;
    this.api = api;
    this.state = state;
    this.deviceName = deviceName;
  }
  async sync() {
    var _a, _b;
    const localFiles = await this.scanLocalFiles();
    const manifest = await this.api.getManifest(this.state.vault_id);
    this.state.last_server_rev = manifest.server_rev;
    const remoteFiles = /* @__PURE__ */ new Map();
    for (const entry of manifest.files) {
      remoteFiles.set(entry.path, entry);
    }
    const result = { uploaded: 0, downloaded: 0, deleted: 0, conflicts: 0, errors: [] };
    const detectedRenames = this.detectHashMatchRenames(localFiles);
    for (const rename of detectedRenames) {
      const remoteOld = remoteFiles.get(rename.oldPath);
      if (remoteOld && !remoteOld.deleted) {
        try {
          await this.api.renameFile(this.state.vault_id, {
            old_path: rename.oldPath,
            new_path: rename.newPath,
            base_server_rev: remoteOld.server_rev,
            device_id: this.state.device_id
          });
          remoteFiles.delete(rename.oldPath);
        } catch (e) {
          result.errors.push(`Rename failed: ${rename.oldPath} -> ${rename.newPath}: ${e}`);
          continue;
        }
      }
      if (this.state.files[rename.oldPath]) {
        this.state.files[rename.newPath] = this.state.files[rename.oldPath];
        delete this.state.files[rename.oldPath];
      }
      localFiles.delete(rename.oldPath);
    }
    for (const [path, localHash] of localFiles) {
      if (this.state.tombstones[path]) {
        syncLog.info(`Skipping upload of tombstoned file: ${path}`);
        continue;
      }
      const remote = remoteFiles.get(path);
      if (!remote) {
        try {
          const resp = await this.uploadFile(path, 0);
          result.uploaded++;
        } catch (e) {
          if (e instanceof UploadConflictError) {
            try {
              await this.handleUploadConflict(path, (_a = e.currentRev) != null ? _a : manifest.server_rev, e.serverSha256);
              result.conflicts++;
            } catch (conflictErr) {
              result.errors.push(`Conflict resolution failed: ${path}: ${conflictErr}`);
            }
          } else {
            result.errors.push(`Upload failed: ${path}: ${e}`);
          }
        }
      } else if (remote.deleted) {
        const localState = this.state.files[path];
        if (localState && localState.sha256 === localHash) {
          try {
            await this.deleteLocalFile(path, remote.server_rev);
            result.deleted++;
          } catch (e) {
            result.errors.push(`Delete failed: ${path}: ${e}`);
          }
        } else {
          try {
            await this.handleUploadConflict(path, remote.server_rev, remote.sha256, localHash);
            result.conflicts++;
          } catch (e) {
            result.errors.push(`Conflict resolution failed: ${path}: ${e}`);
          }
        }
      } else if (remote.sha256 !== localHash) {
        const localState = this.state.files[path];
        if (!localState) {
          try {
            await this.handleUploadConflict(path, remote.server_rev, remote.sha256, localHash);
            result.conflicts++;
          } catch (e) {
            result.errors.push(`Conflict resolution failed: ${path}: ${e}`);
          }
        } else if (localState.sha256 === localHash) {
          try {
            await this.downloadFile(path, remote);
            result.downloaded++;
          } catch (e) {
            result.errors.push(`Download failed: ${path}: ${e}`);
          }
        } else if (remote.sha256 === localState.sha256) {
          try {
            const resp = await this.uploadFile(path, remote.server_rev);
            result.uploaded++;
          } catch (e) {
            if (e instanceof UploadConflictError) {
              try {
                await this.handleUploadConflict(path, (_b = e.currentRev) != null ? _b : manifest.server_rev, e.serverSha256);
                result.conflicts++;
              } catch (conflictErr) {
                result.errors.push(`Conflict resolution failed: ${path}: ${conflictErr}`);
              }
            } else {
              result.errors.push(`Upload failed: ${path}: ${e}`);
            }
          }
        } else {
          try {
            await this.handleUploadConflict(path, remote.server_rev, remote.sha256, localHash);
            result.conflicts++;
          } catch (e) {
            result.errors.push(`Conflict resolution failed: ${path}: ${e}`);
          }
        }
      }
    }
    for (const [path, remote] of remoteFiles) {
      if (remote.deleted) {
        if (!localFiles.has(path) && this.state.files[path]) {
          const capturedRev = this.state.files[path].server_rev;
          delete this.state.files[path];
          this.state.tombstones[path] = { deleted_at: (/* @__PURE__ */ new Date()).toISOString(), server_rev: capturedRev };
        }
        continue;
      }
      if (!localFiles.has(path)) {
        if (this.state.files[path]) {
          try {
            await this.api.deleteFile(this.state.vault_id, path, remote.server_rev, this.state.device_id);
            result.deleted++;
            delete this.state.files[path];
            this.state.tombstones[path] = { deleted_at: (/* @__PURE__ */ new Date()).toISOString(), server_rev: remote.server_rev + 1 };
          } catch (e) {
            result.errors.push(`Delete failed: ${path}: ${e}`);
          }
        } else {
          try {
            await this.downloadFile(path, remote);
            result.downloaded++;
          } catch (e) {
            result.errors.push(`Download failed: ${path}: ${e}`);
          }
        }
      }
    }
    return result;
  }
  async syncIncremental(operations) {
    var _a;
    const result = { uploaded: 0, downloaded: 0, deleted: 0, conflicts: 0, errors: [] };
    const manifest = await this.api.getManifest(this.state.vault_id);
    this.state.last_server_rev = manifest.server_rev;
    const remoteFiles = /* @__PURE__ */ new Map();
    for (const entry of manifest.files) {
      remoteFiles.set(entry.path, entry);
    }
    const tombstones = this.state.tombstones;
    for (const op of operations) {
      try {
        switch (op.type) {
          case "rename": {
            if (!op.oldPath) {
              syncLog.warn(`Rename operation missing oldPath for ${op.path}`);
              continue;
            }
            const remoteOld = remoteFiles.get(op.oldPath);
            if (remoteOld && !remoteOld.deleted) {
              await this.api.renameFile(this.state.vault_id, {
                old_path: op.oldPath,
                new_path: op.path,
                base_server_rev: remoteOld.server_rev,
                device_id: this.state.device_id
              });
            } else {
              syncLog.info(`No active remote entry for rename old path: ${op.oldPath}`);
            }
            if (this.state.files[op.oldPath]) {
              this.state.files[op.path] = this.state.files[op.oldPath];
              delete this.state.files[op.oldPath];
            }
            break;
          }
          case "delete": {
            const remote = remoteFiles.get(op.path);
            if (remote && !remote.deleted) {
              await this.api.deleteFile(this.state.vault_id, op.path, remote.server_rev, this.state.device_id);
              tombstones[op.path] = { deleted_at: (/* @__PURE__ */ new Date()).toISOString(), server_rev: remote.server_rev + 1 };
            } else if (remote && remote.deleted) {
              syncLog.info(`Remote already deleted: ${op.path}`);
            }
            delete this.state.files[op.path];
            break;
          }
          case "create":
          case "modify": {
            if (tombstones[op.path]) {
              syncLog.info(`Skipping upload of tombstoned file: ${op.path}`);
              continue;
            }
            const file = this.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(op.path));
            if (!(file instanceof import_obsidian2.TFile)) {
              syncLog.warn(`File not found for ${op.type}: ${op.path}`);
              continue;
            }
            const buffer = await this.vault.readBinary(file);
            const hash = await sha256ArrayBuffer(buffer);
            const remote = remoteFiles.get(op.path);
            if (!remote) {
              const resp = await this.api.uploadFile(this.state.vault_id, op.path, buffer, hash, 0, this.state.device_id);
              this.state.files[op.path] = {
                sha256: hash,
                server_rev: resp.server_rev,
                last_synced_at: (/* @__PURE__ */ new Date()).toISOString()
              };
              result.uploaded++;
            } else if (remote.deleted) {
              syncLog.info(`Conflict: local ${op.type} vs remote delete for ${op.path}`);
              await this.handleUploadConflict(op.path, remote.server_rev, remote.sha256, hash);
              result.conflicts++;
            } else {
              try {
                const resp = await this.api.uploadFile(this.state.vault_id, op.path, buffer, hash, remote.server_rev, this.state.device_id);
                this.state.files[op.path] = {
                  sha256: hash,
                  server_rev: resp.server_rev,
                  last_synced_at: (/* @__PURE__ */ new Date()).toISOString()
                };
                result.uploaded++;
              } catch (e) {
                if (e.error === "conflict") {
                  const serverSha256 = e.server_sha256;
                  try {
                    await this.handleUploadConflict(op.path, (_a = e.current_rev) != null ? _a : remote.server_rev, serverSha256);
                    result.conflicts++;
                  } catch (conflictErr) {
                    result.errors.push(`Conflict resolution failed: ${op.path}: ${conflictErr}`);
                  }
                } else {
                  result.errors.push(`Upload failed: ${op.path}: ${e}`);
                }
              }
            }
            break;
          }
        }
      } catch (e) {
        result.errors.push(`Operation failed (${op.type} ${op.path}): ${e}`);
      }
    }
    return result;
  }
  detectHashMatchRenames(localFiles) {
    const renames = [];
    const usedLocalPaths = /* @__PURE__ */ new Set();
    for (const [statePath, stateEntry] of Object.entries(this.state.files)) {
      if (localFiles.has(statePath)) {
        continue;
      }
      for (const [localPath, localHash] of localFiles) {
        if (usedLocalPaths.has(localPath)) continue;
        if (localPath !== statePath && stateEntry.sha256 === localHash) {
          renames.push({ oldPath: statePath, newPath: localPath });
          usedLocalPaths.add(localPath);
          break;
        }
      }
    }
    return renames;
  }
  async scanLocalFiles() {
    const files = /* @__PURE__ */ new Map();
    const allFiles = this.vault.getFiles();
    const batchSize = 50;
    for (let i = 0; i < allFiles.length; i += batchSize) {
      const batch = allFiles.slice(i, i + batchSize);
      await Promise.all(batch.map(async (file) => {
        const path = file.path;
        if (shouldIgnorePath(path)) return;
        if (file instanceof import_obsidian2.TFile) {
          const buffer = await this.vault.readBinary(file);
          const hash = await sha256ArrayBuffer(buffer);
          files.set(path, hash);
        }
      }));
      await new Promise((resolve) => setTimeout(resolve, 0));
    }
    return files;
  }
  async uploadFile(path, baseServerRev) {
    const file = this.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(path));
    if (!(file instanceof import_obsidian2.TFile)) {
      throw new Error(`File not found for upload: ${path}`);
    }
    const buffer = await this.vault.readBinary(file);
    const hash = await sha256ArrayBuffer(buffer);
    let resp;
    try {
      resp = await this.api.uploadFile(this.state.vault_id, path, buffer, hash, baseServerRev, this.state.device_id);
    } catch (e) {
      if (e.error === "conflict") {
        throw new UploadConflictError(path, e.server_sha256, e.current_rev);
      }
      throw e;
    }
    this.state.files[path] = {
      sha256: hash,
      server_rev: resp.server_rev,
      last_synced_at: (/* @__PURE__ */ new Date()).toISOString()
    };
    return resp;
  }
  async downloadFile(path, remote) {
    var _a;
    const data = await this.api.downloadFile(this.state.vault_id, path);
    if (remote.sha256) {
      const computedHash = await sha256ArrayBuffer(data);
      if (computedHash !== remote.sha256) {
        throw new Error(`SHA-256 mismatch for ${path}: expected ${remote.sha256}, got ${computedHash}`);
      }
    }
    const normalizedPath = (0, import_obsidian2.normalizePath)(path);
    const lastSlash = normalizedPath.lastIndexOf("/");
    if (lastSlash > 0) {
      const dir = normalizedPath.slice(0, lastSlash);
      await this.vault.adapter.mkdir((0, import_obsidian2.normalizePath)(dir));
    }
    await this.vault.adapter.writeBinary(normalizedPath, data);
    this.state.files[path] = {
      sha256: (_a = remote.sha256) != null ? _a : await sha256ArrayBuffer(data),
      server_rev: remote.server_rev,
      last_synced_at: (/* @__PURE__ */ new Date()).toISOString()
    };
  }
  async deleteLocalFile(path, remoteServerRev) {
    const file = this.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(path));
    if (!(file instanceof import_obsidian2.TFile)) return;
    await this.vault.delete(file);
    delete this.state.files[path];
    if (remoteServerRev !== void 0) {
      this.state.tombstones[path] = { deleted_at: (/* @__PURE__ */ new Date()).toISOString(), server_rev: remoteServerRev };
    }
  }
  async createConflictCopy(path) {
    const file = this.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(path));
    if (!(file instanceof import_obsidian2.TFile)) return;
    let conflictName = formatConflictFileName(path, this.deviceName, /* @__PURE__ */ new Date());
    let counter = 1;
    while (this.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(conflictName))) {
      const lastDot = conflictName.lastIndexOf(".");
      const ext = lastDot > 0 ? conflictName.slice(lastDot) : "";
      const base = lastDot > 0 ? conflictName.slice(0, lastDot) : conflictName;
      conflictName = `${base} (${counter})${ext}`;
      counter++;
    }
    await this.vault.copy(file, (0, import_obsidian2.normalizePath)(conflictName));
  }
  async handleUploadConflict(path, remoteRev, remoteSha256, localHash) {
    await this.createConflictCopy(path);
    if (remoteSha256) {
      const data = await this.api.downloadFile(this.state.vault_id, path);
      const normalizedPath = (0, import_obsidian2.normalizePath)(path);
      const lastSlash = normalizedPath.lastIndexOf("/");
      if (lastSlash > 0) {
        const dir = normalizedPath.slice(0, lastSlash);
        await this.vault.adapter.mkdir((0, import_obsidian2.normalizePath)(dir));
      }
      await this.vault.adapter.writeBinary(normalizedPath, data);
      const hash = remoteSha256 != null ? remoteSha256 : await sha256ArrayBuffer(data);
      this.state.files[path] = {
        sha256: hash,
        server_rev: remoteRev,
        last_synced_at: (/* @__PURE__ */ new Date()).toISOString()
      };
    } else {
      console.log(`Server file ${path} is deleted; local version saved as conflict copy`);
      if (localHash) {
        this.state.files[path] = {
          sha256: localHash,
          server_rev: remoteRev,
          last_synced_at: (/* @__PURE__ */ new Date()).toISOString()
        };
      }
    }
  }
};

// src/state.ts
function createEmptySyncState(vaultId, deviceId, deviceName) {
  return {
    version: 1,
    vault_id: vaultId,
    device_id: deviceId,
    device_name: deviceName,
    last_server_rev: 0,
    files: {},
    tombstones: {}
  };
}
function migrateSyncState(state) {
  var _a, _b;
  const version = (_a = state.version) != null ? _a : 0;
  if (version === 1) {
    return {
      version: 1,
      vault_id: state.vault_id || "",
      device_id: state.device_id || "",
      device_name: state.device_name || "",
      last_server_rev: (_b = state.last_server_rev) != null ? _b : 0,
      files: state.files || {},
      tombstones: state.tombstones || {}
    };
  }
  return createEmptySyncState(state.vault_id || "", state.device_id || "", state.device_name || "");
}
var TOMBSTONE_RETENTION_DAYS = 30;
function pruneTombstones(state) {
  const cutoff = /* @__PURE__ */ new Date();
  cutoff.setDate(cutoff.getDate() - TOMBSTONE_RETENTION_DAYS);
  const cutoffIso = cutoff.toISOString();
  for (const [path, tombstone] of Object.entries(state.tombstones)) {
    if (tombstone.deleted_at < cutoffIso) {
      delete state.tombstones[path];
    }
  }
}

// src/sync-queue.ts
var SyncQueue = class {
  constructor(options, onSync) {
    this.options = options;
    this.onSync = onSync;
    __publicField(this, "pending", /* @__PURE__ */ new Map());
    __publicField(this, "offlineQueue", []);
    __publicField(this, "debounceTimer", null);
    __publicField(this, "retryTimer", null);
    __publicField(this, "retryCount", 0);
    __publicField(this, "isRunning", false);
    __publicField(this, "online", true);
    __publicField(this, "active", false);
    __publicField(this, "lastRetryAfterMs");
  }
  add(op) {
    if (op.type === "rename" && op.oldPath) {
      const existing = this.pending.get(op.oldPath);
      if (existing) {
        this.pending.delete(op.oldPath);
        const updatedOp = {
          path: op.path,
          type: existing.type === "create" ? "create" : "rename",
          oldPath: existing.type === "create" ? void 0 : op.oldPath
        };
        this.pending.set(op.path, updatedOp);
        this.scheduleRun();
        return;
      }
    }
    this.pending.set(op.path, op);
    this.scheduleRun();
  }
  flush() {
    this.clearDebounceTimer();
    void this.runSync();
  }
  start() {
    this.active = true;
  }
  stop() {
    this.active = false;
    this.clearTimers();
  }
  isOnline() {
    return this.online;
  }
  setOnline(online) {
    const wasOffline = !this.online;
    this.online = online;
    if (online && wasOffline) {
      this.retryCount = 0;
      this.clearRetryTimer();
      for (const op of this.offlineQueue) {
        this.pending.set(op.path, op);
      }
      this.offlineQueue = [];
      this.flush();
    }
  }
  getPendingCount() {
    return this.pending.size;
  }
  getOfflineQueueCount() {
    return this.offlineQueue.length;
  }
  scheduleRun() {
    if (!this.active) return;
    this.clearDebounceTimer();
    this.debounceTimer = window.setTimeout(() => {
      this.debounceTimer = null;
      void this.runSync();
    }, this.options.debounceMs);
  }
  async runSync() {
    if (this.isRunning) return;
    const ops = Array.from(this.pending.values());
    if (ops.length === 0) return;
    this.pending.clear();
    this.isRunning = true;
    try {
      await this.onSync(ops);
      this.retryCount = 0;
    } catch (error) {
      if ((error == null ? void 0 : error.status) === 409) {
        throw error;
      }
      if ((error == null ? void 0 : error.status) === 429 && typeof (error == null ? void 0 : error.retry_after) === "number" && !Number.isNaN(error.retry_after)) {
        this.lastRetryAfterMs = error.retry_after * 1e3;
      }
      if (this.isRetryableError(error)) {
        this.online = false;
        const maxOfflineQueue = 1e3;
        if (this.offlineQueue.length + ops.length > maxOfflineQueue) {
          const toDrop = this.offlineQueue.length + ops.length - maxOfflineQueue;
          this.offlineQueue = this.offlineQueue.slice(toDrop);
          console.warn(`Dropped ${toDrop} oldest operations from offline queue (max ${maxOfflineQueue})`);
        }
        this.offlineQueue.push(...ops);
        this.scheduleRetry();
      } else {
        console.error("Sync queue error (non-retryable):", error);
      }
    } finally {
      this.isRunning = false;
    }
  }
  scheduleRetry() {
    if (!this.active) return;
    if (this.retryCount >= this.options.maxRetries) return;
    this.clearRetryTimer();
    let delay;
    if (this.lastRetryAfterMs !== void 0 && !Number.isNaN(this.lastRetryAfterMs)) {
      delay = Math.min(this.lastRetryAfterMs, this.options.retryMaxDelayMs) + Math.floor(Math.random() * 500);
    } else {
      delay = Math.min(this.options.retryBaseDelayMs * Math.pow(2, this.retryCount) + Math.floor(Math.random() * 1e3), this.options.retryMaxDelayMs);
    }
    this.lastRetryAfterMs = void 0;
    this.retryCount++;
    this.retryTimer = window.setTimeout(() => {
      this.retryTimer = null;
      for (const op of this.offlineQueue) {
        this.pending.set(op.path, op);
      }
      this.offlineQueue = [];
      void this.runSync();
    }, delay);
  }
  clearTimers() {
    this.clearDebounceTimer();
    this.clearRetryTimer();
  }
  clearDebounceTimer() {
    if (this.debounceTimer !== null) {
      window.clearTimeout(this.debounceTimer);
      this.debounceTimer = null;
    }
  }
  clearRetryTimer() {
    if (this.retryTimer !== null) {
      window.clearTimeout(this.retryTimer);
      this.retryTimer = null;
    }
  }
  isNetworkError(error) {
    if (error instanceof TypeError) return true;
    if (error instanceof Error) {
      const msg = error.message;
      if (msg.includes("fetch") || msg.includes("network") || msg.includes("offline") || msg.includes("Failed to fetch")) {
        return true;
      }
      if (error.status === 429) {
        return true;
      }
    }
    return false;
  }
  isRetryableError(error) {
    if (this.isNetworkError(error)) return true;
    const status = error == null ? void 0 : error.status;
    if (status === 429) return true;
    if (typeof status === "number" && status >= 500 && status < 600) return true;
    const msg = (error == null ? void 0 : error.message) || "";
    if (/^HTTP 429:/.test(msg)) return true;
    if (/^HTTP 5\d\d:/.test(msg)) return true;
    return false;
  }
};

// src/main.ts
var RustShareVaultSyncPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "statusBar");
    __publicField(this, "syncState", null);
    __publicField(this, "syncQueue");
    __publicField(this, "syncInterval", null);
    __publicField(this, "isSyncing", false);
  }
  async onload() {
    var _a, _b;
    await this.loadSettings();
    if (!this.settings.deviceName) {
      this.settings.deviceName = `${this.app.vault.getName()} - ${navigator.platform}`;
      await this.saveSettings();
    }
    this.statusBar = new StatusBar(this);
    this.syncQueue = new SyncQueue(
      {
        debounceMs: this.settings.debounceMs,
        maxRetries: this.settings.maxRetries,
        retryBaseDelayMs: this.settings.retryBaseDelayMs,
        retryMaxDelayMs: 6e4
      },
      async (ops) => {
        if (!this.settings.vaultId) {
          syncLog.debug("Sync queue: no vault configured, skipping");
          return;
        }
        if (this.isSyncing) {
          syncLog.debug("Sync queue: full sync in progress, skipping incremental");
          return;
        }
        await this.runIncrementalSync(ops);
      }
    );
    this.syncQueue.start();
    this.addRibbonIcon("cloud", "RustShare Vault Sync", (evt) => {
      this.runManualSync();
    });
    this.addCommand({
      id: "rustshare-sync-vault",
      name: "Sync vault to RustShare",
      callback: () => this.runManualSync()
    });
    this.addCommand({
      id: "rustshare-connect-vault",
      name: "Connect or create vault",
      callback: () => this.connectVault()
    });
    this.addSettingTab(new RustShareVaultSyncSettingTab(this.app, this));
    if (this.settings.autoSyncIntervalMinutes > 0) {
      this.startAutoSync();
    }
    this.registerEvent(this.app.vault.on("create", (file) => {
      if (file instanceof import_obsidian3.TFile && !shouldIgnorePath(file.path)) {
        syncLog.debug("Event: create", file.path);
        this.syncQueue.add({ path: file.path, type: "create" });
      }
    }));
    this.registerEvent(this.app.vault.on("delete", (file) => {
      if (file instanceof import_obsidian3.TFile && !shouldIgnorePath(file.path)) {
        syncLog.debug("Event: delete", file.path);
        this.syncQueue.add({ path: file.path, type: "delete" });
      }
    }));
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      if (file instanceof import_obsidian3.TFile && !shouldIgnorePath(file.path)) {
        syncLog.debug("Event: rename", `${oldPath} -> ${file.path}`);
        this.syncQueue.add({ path: file.path, type: "rename", oldPath });
      }
    }));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (file instanceof import_obsidian3.TFile && !shouldIgnorePath(file.path)) {
        syncLog.debug("Event: modify", file.path);
        this.syncQueue.add({ path: file.path, type: "modify" });
      }
    }));
    this.registerDomEvent(window, "online", () => {
      syncLog.info("Network online detected");
      this.syncQueue.setOnline(true);
    });
    this.registerDomEvent(window, "offline", () => {
      syncLog.info("Network offline detected");
      this.syncQueue.setOnline(false);
    });
    const vaultPath = ((_b = (_a = this.app.vault.adapter).getBasePath) == null ? void 0 : _b.call(_a)) || "";
    const cloudFolder = detectCloudSyncFolder(vaultPath);
    if (cloudFolder) {
      new import_obsidian3.Notice(
        `Warning: This vault appears to be inside ${cloudFolder}. Using multiple sync engines on the same vault can cause conflicts.`,
        1e4
      );
    }
  }
  onunload() {
    this.stopAutoSync();
    this.syncQueue.stop();
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    if (data == null ? void 0 : data.syncState) {
      this.syncState = migrateSyncState(data.syncState);
    }
  }
  async saveSettings() {
    await this.saveData({ ...this.settings, syncState: this.syncState });
  }
  async connectVault() {
    if (!this.settings.rustshareUrl) {
      new import_obsidian3.Notice("Please enter your RustShare URL in settings first.");
      return;
    }
    const api = new RustShareAPI(this.settings.rustshareUrl, "");
    try {
      this.statusBar.updateStatus("syncing", "Requesting device pairing...");
      const pairing = await api.requestDevicePairing();
      const verificationUrl = pairing.verification_uri_complete || pairing.verification_uri;
      const formattedCode = `${pairing.user_code.slice(0, 4)}-${pairing.user_code.slice(4)}`;
      new import_obsidian3.Notice(
        `Pairing code: ${formattedCode}. Go to ${verificationUrl} and approve.`,
        3e4
        // 30 seconds
      );
      this.statusBar.updateStatus("syncing", `Waiting for approval (code: ${formattedCode})...`);
      let token = null;
      const startTime = Date.now();
      const maxWaitMs = pairing.expires_in * 1e3;
      while (Date.now() - startTime < maxWaitMs) {
        await new Promise((resolve) => setTimeout(resolve, 3e3));
        const poll = await api.pollDevicePairing(pairing.device_code);
        if (poll.status === "approved") {
          token = poll.token;
          break;
        } else if (poll.status === "expired") {
          throw new Error("Pairing code expired. Please try again.");
        }
      }
      if (!token) {
        throw new Error("Pairing timed out. Please try again.");
      }
      this.settings.authToken = token;
      await this.saveSettings();
      new import_obsidian3.Notice("Device paired successfully!");
      const authedApi = new RustShareAPI(this.settings.rustshareUrl, token);
      let deviceId;
      try {
        const resp = await authedApi.registerDevice(this.settings.deviceName, "obsidian_plugin", "0.1.0");
        deviceId = resp.id;
        this.settings.deviceId = deviceId;
        await this.saveSettings();
      } catch (e) {
        const isNetworkError = e instanceof TypeError || /fetch|network|Failed to fetch/i.test((e == null ? void 0 : e.message) || "");
        if (this.settings.deviceId) {
          deviceId = this.settings.deviceId;
          if (isNetworkError) {
            console.info("Using cached device ID due to network error during registration:", e);
          } else {
            console.warn("Using cached device ID, registration failed:", e);
          }
        } else {
          throw new Error(`Failed to register device: ${e.message || e}`);
        }
      }
      let vaultId = this.settings.vaultId;
      if (!vaultId) {
        const vault = await authedApi.createVault({
          name: this.app.vault.getName(),
          adapter: "obsidian_vault",
          client_vault_id: void 0,
          device_id: this.settings.deviceId
        });
        vaultId = vault.id;
        this.settings.vaultId = vaultId;
        await this.saveSettings();
        new import_obsidian3.Notice(`Created vault: ${vault.name}`);
      } else {
        const vault = await authedApi.getVault(vaultId);
        new import_obsidian3.Notice(`Connected to vault: ${vault.name}`);
      }
      if (!this.syncState || this.syncState.vault_id !== vaultId || this.syncState.device_id !== deviceId) {
        this.syncState = createEmptySyncState(vaultId, deviceId, this.settings.deviceName);
      }
      this.statusBar.updateStatus("connected");
    } catch (e) {
      this.statusBar.updateStatus("error", `Connect failed: ${e}`);
      new import_obsidian3.Notice(`Failed to connect: ${e}`);
    }
  }
  async runManualSync() {
    if (this.isSyncing) {
      new import_obsidian3.Notice("Sync already in progress");
      return;
    }
    this.isSyncing = true;
    try {
      if (!this.settings.vaultId) {
        new import_obsidian3.Notice('No vault configured. Run "Connect or create vault" first.');
        this.isSyncing = false;
        return;
      }
      if (!this.syncState) {
        this.syncState = createEmptySyncState(
          this.settings.vaultId,
          this.settings.deviceId,
          this.settings.deviceName
        );
      }
      const api = new RustShareAPI(this.settings.rustshareUrl, this.settings.authToken);
      const engine = new SyncEngine(this.app.vault, api, this.syncState, this.settings.deviceName);
      try {
        this.statusBar.updateStatus("syncing", "Syncing...");
        const result = await engine.sync();
        await this.saveSettings();
        if (this.syncState) {
          pruneTombstones(this.syncState);
        }
        const msg = `Sync complete: ${result.uploaded}\u2191 ${result.downloaded}\u2193 ${result.deleted}\u{1F5D1} ${result.conflicts}\u26A0`;
        if (result.errors.length > 0) {
          this.statusBar.updateStatus("error", `${msg} (${result.errors.length} errors)`);
          console.error("Sync errors:", result.errors);
        } else if (result.conflicts > 0) {
          this.statusBar.updateStatus("conflict", msg);
        } else {
          this.statusBar.updateStatus("synced", msg);
        }
        new import_obsidian3.Notice(msg, 4e3);
        this.syncQueue.setOnline(true);
      } catch (e) {
        this.statusBar.updateStatus("error", `Sync failed: ${e}`);
        new import_obsidian3.Notice(`Sync failed: ${e}`);
      }
    } finally {
      this.isSyncing = false;
    }
  }
  async runIncrementalSync(ops) {
    if (!this.settings.vaultId || !this.syncState) {
      syncLog.debug("Incremental sync: no vault or state");
      return;
    }
    this.isSyncing = true;
    try {
      const api = new RustShareAPI(this.settings.rustshareUrl, this.settings.authToken);
      const engine = new SyncEngine(this.app.vault, api, this.syncState, this.settings.deviceName);
      this.statusBar.updateStatus("syncing", "Syncing...");
      const result = await engine.syncIncremental(ops);
      await this.saveSettings();
      if (this.syncState) {
        pruneTombstones(this.syncState);
      }
      const msg = `Incremental sync: ${result.uploaded}\u2191 ${result.downloaded}\u2193 ${result.deleted}\u{1F5D1} ${result.conflicts}\u26A0`;
      if (result.errors.length > 0) {
        this.statusBar.updateStatus("error", `${msg} (${result.errors.length} errors)`);
        console.error("Incremental sync errors:", result.errors);
      } else if (result.conflicts > 0) {
        this.statusBar.updateStatus("conflict", msg);
      } else {
        this.statusBar.updateStatus("synced", msg);
      }
      if (this.settings.logSyncEvents) {
        syncLog.info(msg);
      }
      this.syncQueue.setOnline(true);
    } catch (e) {
      this.statusBar.updateStatus("error", `Incremental sync failed: ${e}`);
      syncLog.error("Incremental sync failed", void 0, String(e));
      throw e;
    } finally {
      this.isSyncing = false;
    }
  }
  startAutoSync() {
    if (this.syncInterval) return;
    const ms = this.settings.autoSyncIntervalMinutes * 60 * 1e3;
    this.syncInterval = window.setInterval(() => this.runManualSync(), ms);
  }
  stopAutoSync() {
    if (this.syncInterval) {
      window.clearInterval(this.syncInterval);
      this.syncInterval = null;
    }
  }
};
