[package]
name = "rustshare-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
argon2.workspace = true
rand.workspace = true
thiserror.workspace = true
aes-gcm = "0.10"
base64 = { version = "0.22", features = ["alloc"] }
